name: Test CI
on:
  push:
    paths:
    - '**.ring'
    - '**.dll'
    - '**.so'
    - '**.dylib'
    - '.github/workflows/testCI.yml'

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Run Ring YAML tests
      uses: ysdragon/ring-action@v1.2.2
      with:
        file: "tests/YAML_test.ring"
